### ISSUE TITLE
New typing-extensions version scheme

### ISSUE THREAD

**Issue by pejter** [MousaZeidBaker/aws-lambda-typing#37]
Recently typing-extensions switched to semantic versioning and bumped the version to 4.0.0
[](https://github.com/python/typing/blob/master/typing_extensions/README.rst)

The library dependencies right now specify ^3.10.0 which means 4.X is deemed incompatible and as such the library isn't compatible with the new versioning scheme.

Also the only feature this library needs is TypedDict so you can forego the dependency on typing-extensions for Python versions starting from 3.8
I don't know if poetry allows the same controls but in vanilla setup.cfg you can declare it like this:
```ini

install_requires =
    typing-extensions; python_version < "3.8"

**Comment by MousaZeidBaker** [comment]
Thanks for reporting an issue @pejter 

Could you please elaborate more about the issue? There will always be outdated dependencies, we just need to keep them up to date. So can't we just upgrade our `typing-extensions` dependency to 4.x?

We use other types from `typing-extensions` as well, such as `Final` & `Literal`, [see here](https://github.com/MousaZeidBaker/aws-lambda-typing/blob/master/src/aws_lambda_typing/events/ses.py#L19).

**Comment by pejter** [comment]
That's what I mean. To update the dependency spec to include the new versioning scheme.

And both `Final` & `Literal` were introduced in 3.8 so my suggestion about conditionally depending on typing-extensions still applies.
