### ISSUE TITLE
mypy errors for CloudFormation custom resource types

### ISSUE THREAD

**Issue by chuckwondo** [MousaZeidBaker/aws-lambda-typing#41]
When running `mypy src`, I see the following errors:

```plain
src/aws_lambda_typing/events/cloud_formation_custom_resource.py:83: error: Overwriting TypedDict field "RequestType" while merging
src/aws_lambda_typing/events/cloud_formation_custom_resource.py:83: error: Overwriting TypedDict field "RequestId" while merging
src/aws_lambda_typing/events/cloud_formation_custom_resource.py:83: error: Overwriting TypedDict field "ResponseURL" while merging
src/aws_lambda_typing/events/cloud_formation_custom_resource.py:83: error: Overwriting TypedDict field "ResourceType" while merging
src/aws_lambda_typing/events/cloud_formation_custom_resource.py:83: error: Overwriting TypedDict field "LogicalResourceId" while merging
src/aws_lambda_typing/events/cloud_formation_custom_resource.py:83: error: Overwriting TypedDict field "StackId" while merging
src/aws_lambda_typing/events/cloud_formation_custom_resource.py:83: error: Overwriting TypedDict field "ResourceProperties" while merging
src/aws_lambda_typing/events/cloud_formation_custom_resource.py:83: error: Overwriting TypedDict field "PhysicalResourceId" while merging
Found 8 errors in 1 file (checked 34 source files)
```

This occurs because of the following in the indicated file (doc comments removed):

```python
class CloudFormationCustomResourceEvent(
    CloudFormationCustomResourceUpdate,
    CloudFormationCustomResourceDelete,
):
    pass
```

and both `CloudFormationCustomResourceUpdate` and `CloudFormationCustomResourceDelete` extend `CloudFormationCustomResourceCommon`.

I don't know the reasoning behind structuring the types this way, but perhaps a slight refactoring along the following lines would be an acceptable way to eliminate these errors, and also provide additional type safety.

First, remove `RequestType` from `CloudFormationCustomResourceCommon` so that each extension is required to specify the corresponding Literal type.

Then, define `CloudFormationCustomResourceCreate`, which is missing:

```python
class CloudFormationCustomResourceCreate(
    CloudFormationCustomResourceCommon,
    total=False,
):
    RequestType: Literal["Create"]
```

Similarly, for `CloudFormationCustomResourceUpdate` and `CloudFormationCustomResourceDelete`, set `RequestType` to `Literal["Update"]` and `Literal["Delete"]`, respectively.

Finally, define `CloudFormationCustomResourceEvent` as `Union[CloudFormationCustomResourceCreate, CloudFormationCustomResourceUpdate, CloudFormationCustomResourceDelete]` to eliminate the mypy errors above.

**Comment by MousaZeidBaker** [comment]
Hi @chuckwondo, thanks for your contribution.

The structure you see is [TypedDict inheritance](https://www.python.org/dev/peps/pep-0589/#inheritance) and is valid. It seems mypy is interpreting it wrong, and there is an [issue reported](https://github.com/python/mypy/issues/8714).

**Comment by chuckwondo** [comment]
Regarding the Create type, I think having the "common" type represent the Create type is not ideal, as it's not obvious.

Regarding the typing error in the previous screenshots, that's to be expected. From the "producer" end of things, you'll use the specific types when _producing_ an event. On the "consumer" end (i.e., as an event _handler_), you'll use the generic type, and then use the value of the "tag" (`RequestType`) to narrow the type.

For example:
```
def handle_event(event: CloudFormationCustomResourceEvent) -> None:
    if event["RequestType"] == "Update":
        # event is automatically narrowed to CloudFormationCustomResourceUpdate
        old_properties = event["OldResourceProperties"]
```

See [mypy's documentation on tagged unions](https://mypy.readthedocs.io/en/latest/literal_types.html#tagged-unions).

**Comment by chuckwondo** [comment]
I've updated the PR with a couple more tweaks, and a new test that uses the generic event type, showing automatic type narrowing.

**Comment by MousaZeidBaker** [comment]
> Regarding the Create type, I think having the "common" type represent the Create type is not ideal, as it's not obvious.

Agree!


> Regarding the typing error in the previous screenshots, that's to be expected. From the "producer" end of things, you'll use the specific types when producing an event. On the "consumer" end (i.e., as an event handler), you'll use the generic type, and then use the value of the "tag" (RequestType) to narrow the type.

I understand this, and I was talking from a consumer point of view because as you already mention they will use `CloudFormationCustomResourceEvent` in the handler and it failed previously, but it seems that they work now after your latest changes. Thats also why I in the tests use the types that the consumer will use the handlers. 

I still think we should add the previous docstring to the `CloudFormationCustomResourceEvent` variable, because as you can see the current docstring when you hover over it is not so helpful.
![image](https://user-images.githubusercontent.com/16031346/149567028-58b236d2-34c8-4825-805f-400b68db2c53.png)

**Comment by MousaZeidBaker** [comment]
Also, now that `mypy src` works, can you add the command as an extra sanity check to the workflows: [here](https://github.com/MousaZeidBaker/aws-lambda-typing/blob/master/.github/workflows/publish.yaml#L40), [here](https://github.com/MousaZeidBaker/aws-lambda-typing/blob/master/.github/workflows/publish.yaml#L80), and [here](https://github.com/MousaZeidBaker/aws-lambda-typing/blob/master/.github/workflows/test.yaml#L44).

**Comment by chuckwondo** [comment]
Cool. I appreciate your prompt replies, and I'll work on your latest change requests.

Removing `total=False` is what allows things to work like you show in your latest screenshot.

Also, just to clarify a bit more on the producer/consumer topic, I consider your pre-existing test functions to be "producer" functions because you are producing an object (as a literal dict expression) in each one (even though you don't actually do anything with it, such as pass it to a "consuming" function). These functions are representative of what occurs on the CloudFormation side, where the events are produced.

For example, I consider the following a "producer" function, which is why it doesn't really make sense to type `event` generally as `CloudFormationCustomResourceEvent`. In this case, since we are producing (creating) the object, we know it's specific type, because we're producing it, so we use the specific type:
```python
def test_cloud_formation_custom_resource_create_event() -> None:
    event: CloudFormationCustomResourceCreate = {
        "RequestType": "Create",
        "RequestId": "unique id for this create request",
        "ResponseURL": "pre-signed-url-for-create-response",
        "ResourceType": "Custom::MyCustomResourceType",
        "LogicalResourceId": "name of resource in template",
        "StackId": "arn:aws:cloudformation:us-east-2:123456789012:stack/mystack-sggfrhxhum7w/f449b250-b969-11e0-a185-5081d0136786",  # noqa: E501
        "ResourceProperties": {
            "key1": "new-string",
            "key2": ["new-list"],
            "key3": {"key4": "new-map"},
        },
    }
```

That's why I added an addition test function to act as a "consumer", where we don't know in advance the specific type, so we use the "general" type, and use the "tag" (the `RequestType` property in our case) to discern the specific type:
```python
def test_handle_cloud_formation_custom_resource_event(
    event: CloudFormationCustomResourceEvent,
) -> None:
    if event["RequestType"] == "Update":
        # event is automatically narrowed to CloudFormationCustomResourceUpdate
        old_properties = event["OldResourceProperties"]
```

That way, these are more representative of "real" code, since the producer functions are actually on the CloudFormation side (i.e., they're not functions we would actually write because CloudFormation is the producer of the events), and the consumer function is what we would write to handle (consume) events appropriately.
