### ISSUE TITLE
EventBridge

### ISSUE THREAD

**Issue by danielmitchell** [MousaZeidBaker/aws-lambda-typing#49]
We are using EventBridge, which as you no doubt know is the successor to CloudWatch Events -

> Amazon EventBridge is the preferred way to manage your events. CloudWatch Events and EventBridge are the same underlying service and API, but EventBridge provides more features.

The CloudWatchEventsMessageEvent provides the correct typing, but the name adds a bit of confusion since it adds some inconsistency with naming. It's easy for us to alias it internally but I think it would be good if this library had Event Bridge natively, e.g. EventBridgeEvent.

Thanks for providing this library since it allows for a much nicer developer experience.

**Comment by MousaZeidBaker** [comment]
Hi @danielmitchell, thanks for reporting an issue. 

Yeah I'm familiar with this issue, wanted to fix it but did not prioritize it. I do agree that we should add an `EventBridgeEvent`, will do so.
