### ISSUE TITLE
Custom SNS Events via sns:Publish

### ISSUE THREAD

**Issue by tekdj7** [MousaZeidBaker/aws-lambda-typing#53]
Support for custom SNS events done via [sns:Publish](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sns.html#SNS.Client.publish).

**Comment by MousaZeidBaker** [comment]
@tekdj7 could you try this version and let me know if it works as intended? 

You can install from branch as following:

```
poetry add git+https://github.com/MousaZeidBaker/aws-lambda-typing.git#feat/sns-publish-requests
```
