### ISSUE TITLE
Values that can be null should be Optional

### ISSUE THREAD

**Issue by AGiantSquid** [MousaZeidBaker/aws-lambda-typing#79]
Certain fields are able to be `null` values. For example, here are the AWS docs for an API Gateway Event:

![image](https://user-images.githubusercontent.com/26531374/217702679-ab6d153c-45c7-4b45-8780-47f0de13035a.png)

https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html#apigateway-example-event

This `body` field, for example, is currently set to `str`

https://github.com/MousaZeidBaker/aws-lambda-typing/blob/master/src/aws_lambda_typing/events/api_gateway_proxy.py#L181

I think it should be `body: Optional[str]`

Let me know if I should do a PR

**Comment by MousaZeidBaker** [comment]
Thanks for reporting an issue @AGiantSquid 

If you like so, please open a PR. Keep in mind, in TypedDict terms, `Optional[str]` means `str or None` not potentially-missing, see [here](https://peps.python.org/pep-0655/#:~:text=The%20difficulty%20is,not%20potentially%2Dmissing!). For potentially-missing keys, the [totality](https://peps.python.org/pep-0589/#totality) of the dict must be set to false.

**Comment by MousaZeidBaker** [comment]
closed by #80
