### ISSUE TITLE
Powertools for AWS Lambda (Python)

### ISSUE THREAD

**Issue by estahn** [MousaZeidBaker/aws-lambda-typing#89]
Hi @MousaZeidBaker,

Thanks for the great project. We've been using it for a while.

I wonder if [Powertools for AWS Lambda (Python)](https://docs.powertools.aws.dev/lambda/python/latest/) supersedes this project?

**Comment by MousaZeidBaker** [comment]
Hi @estahn, 

I'm glad you like it :)

Powertools provides different [features](https://docs.powertools.aws.dev/lambda/python/latest/#features), however their [typing](https://docs.powertools.aws.dev/lambda/python/latest/utilities/typing/) feature seems to be poor compared to this project. I can only see typing for the `context` class, which isn't often used in Lambdas.  This project provides typings for almost all the different Lambda use cases such as SQS, SNS, S3 etc. So I'd say Powertools doesn't supersedes this project.
